//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitverse.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegenerationTestClasses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegenerationTestClasses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unitverse.Core.Tests.RegenerationTestClasses", typeof(RegenerationTestClasses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace.SubNameSpace
        ///{
        ///    public class TestClass
        ///    {
        ///        public TestClass(string stringProp)
        ///        {
        ///
        ///        }
        /// 
        ///	    public void ThisIsAMethod(string methodName, int methodValue)
        ///	    {
        ///		    System.Console.WriteLine(&quot;Testing this&quot;);
        ///	    }
        ///
        ///        public string WillReturnAString()
        ///        {
        ///            return &quot;Hello&quot;;
        ///        }
        ///    }
        ///}
        ///-------------------
        ///namespace TestNamespace.SubNameSpace
        ///{
        ///    public class TestClass
        ///    {
        ///        public TestClass(str [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Regeneration_SampleClass {
            get {
                return ResourceManager.GetString("Regeneration-SampleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // # EmitUsingsOutsideNamespace=true
        ///namespace TestNamespace.SubNameSpace
        ///{
        ///    public class TestClass
        ///    {
        ///        public TestClass(string stringProp)
        ///        {
        ///
        ///        }
        /// 
        ///	    public void ThisIsAMethod(string methodName, int methodValue)
        ///	    {
        ///		    System.Console.WriteLine(&quot;Testing this&quot;);
        ///	    }
        ///
        ///        public string WillReturnAString()
        ///        {
        ///            return &quot;Hello&quot;;
        ///        }
        ///    }
        ///}
        ///-------------------
        ///namespace TestNamespace.SubNameSpace
        ///{
        ///    public class TestClas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Regeneration_UsingsOutsideNamespace {
            get {
                return ResourceManager.GetString("Regeneration-UsingsOutsideNamespace", resourceCulture);
            }
        }
    }
}
