//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitverse.ExampleGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Examples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Examples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unitverse.ExampleGenerator.Examples", typeof(Examples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace.SubNameSpace
        ///{
        ///	using System;
        ///
        ///    public class SomePoco
        ///    {
        ///        public int Identity { get; set; }
        ///        public string Description { get; set; }
        ///        public Guid UniqueCode { get; set; }
        ///    }
        ///
        ///    public class TestClass
        ///    {
        ///		SomePoco _poco;
        ///
        ///        public TestClass(SomePoco poco)
        ///        {
        ///			_poco = poco;
        ///        }
        /// 
        ///        public SomePoco Poco =&gt; _poco;
        ///    }
        ///}.
        /// </summary>
        internal static string PocoInitialization {
            get {
                return ResourceManager.GetString("PocoInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace.SubNameSpace
        ///{
        ///	using System;
        ///
        ///    public class SomePoco
        ///    {
        ///        public int Identity { get; set; }
        ///        public string Description { get; set; }
        ///        public Guid UniqueCode { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string SimplePoco {
            get {
                return ResourceManager.GetString("SimplePoco", resourceCulture);
            }
        }
    }
}
