// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SentryOne.UnitTestGenerator.Specs.MockGeneration
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Mock Generation")]
    public partial class MockGenerationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MockGeneration.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Mock Generation", "\tI am checking to see if different Mock types work", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Mock Generation Test")]
        [NUnit.Framework.TestCaseAttribute("FakeItEasy", "_iTest = A.Fake<ITest>();", null)]
        [NUnit.Framework.TestCaseAttribute("Moq", "_iTest = new Mock<ITest>().Object;", null)]
        [NUnit.Framework.TestCaseAttribute("NSubstitute", "_iTest = Substitute.For<ITest>();", null)]
        [NUnit.Framework.TestCaseAttribute("RhinoMocks", "_iTest = MockRepository.GenerateStub<ITest>();", null)]
        public virtual void MockGenerationTest(string mock, string statement, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mock Generation Test", null, exampleTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
#line 5
 testRunner.Given("I have a class defined as", @"namespace TestNamespace.SubNameSpace
{

  public interface ITest
  {
      int ThisIsAProperty {get;set;}
  }

  public class TestClass
  {
      public TestClass(string stringProp, ITest iTest)
      {

      }

      public TestClass(int? nullableIntProp, ITest iTest)
      {

      }

      public TestClass(int thisIsAProperty, ITest iTest)
      {

      }
public void ThisIsAMethod(string methodName, int methodValue)
   {
    System.Console.WriteLine(""Testing this"");
   }

      public string WillReturnAString()
      {
          return ""Hello"";
      }

      private string _thisIsAString = string.Empty;
      public string ThisIsAWriteOnlyString { set { _thisIsAString = value; }}

      public int ThisIsAProperty { get;set;}

      public ITest GetITest { get; }

      public TestClass ThisClass {get;set;}
  }
}", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 52
 testRunner.And("I set my test framework to \'NUnit3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And(string.Format("I set my mock framework to \'{0}\'", mock), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.When("I generate tests for the class using strategy \'StandardClassGenerationStrategy\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.Then("I expect the method \'SetUp\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
  testRunner.And(string.Format("I expect it to contain the statement \'{0}\'", statement), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
